[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.default.solidity]
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${SEPOLIA_ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
