name: Deployment Verification

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/services/deployment/**'
      - 'contracts/**'

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd backend && npm install
          cd ../frontend && npm install

      - name: Run deployment verification
        run: |
          cd backend && npm run verify-deployment
